---
title: "bassinat"
author: "Lindsey Weyant"
date: "12/2/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidymodels)
library(dplyr)
library(readr)
inat <- read_csv("inat.csv")
```

```{r kingdomplot}
inat%>%
  ggplot(aes(x = taxon_kingdom_name)) +
  geom_bar() +
  labs(x = "Kingdom Name", y = "Count", title = "Kingdoms of the ECWA Watershed")
```

```{r fungi}
inatfungi <- inat %>%
  filter(taxon_kingdom_name == "Fungi")
```
```{r fungicount}
inatfungi %>%
  count(scientific_name)
```
```{r protozoa}
inatprotozoa <- inat %>%
  filter(taxon_kingdom_name == "Protozoa")
```
```{r protozoacount}
inatprotozoa %>%
  count(scientific_name)
```
```{r animalia}
inatanimalia <- inat %>%
  filter(taxon_kingdom_name == "Animalia")
```
```{r animaliacount}
inatanimalia %>%
    count(scientific_name, sort=TRUE)
```
```{r plantae}
inatplantae <- inat %>%
  filter(taxon_kingdom_name == "Plantae")
```
```{r plantaecount}
inatplantae %>%
  count(scientific_name)
```

2 most common kingdoms: animalia and plantae

```{r animaliaplot}
inatanimalia %>%
  ggplot(aes(x=taxon_class_name)) +
  geom_bar() +
  scale_x_discrete(guide = guide_axis(n.dodge=3)) +
  labs(x= "Class Name", y = "Count", title = "Animalia Observations by Class")
```

```{r insectacount}
inatanimalia %>%
  filter(taxon_class_name == "Insecta") %>%
count(scientific_name, sort = TRUE)
```

```{r avescount}
inatanimalia %>%
  filter(taxon_class_name == "Aves") %>%
count(scientific_name, sort = TRUE)
```

```{r amphibiacount}
inatanimalia %>%
  filter(taxon_class_name == "Amphibia") %>%
  count(scientific_name, sort = TRUE)
```

```{r reptiliacount}
inatanimalia %>%
  filter(taxon_class_name == "Reptilia") %>%
count(scientific_name, sort = TRUE)
```

```{r plantaeplot}
inatplantae %>%
  ggplot(aes(x=taxon_class_name)) +
  geom_bar() +
  scale_x_discrete(guide = guide_axis(n.dodge=3)) +
  labs(x= "Class Name", y = "Count", title = "Plantae Observations by Class")
```

```{r floweringplantscount}
inatplantae %>%
  filter(taxon_class_name == "Magnoliopsida") %>%
count(scientific_name, sort = TRUE)
```

```{r nonfloweringplantscount}
inatplantae %>%
  filter(taxon_class_name == "Liliopsida") %>%
count(scientific_name, sort = TRUE)
```




